apiVersion: v1
kind: Service
metadata: 
  name: food-spring-svc
spec:
  type: NodePort
  selector:
    food: spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30032    
